#Menghitung a,b dan c
a = int(input("Masukkan Nilai a: "))
b = int(input("Masukan Nilai b: "))
c = int(input("Masukan Nilai c: "))
rumus = (a+b)*(a-c)
print(".................")
print("Hasil perhitungan pada a dan b")
print(".................")
print("nilai a: ",a)
print("nilai b: ",b)
print("nilai c: ",c)
print("nilai rumus: ",rumus)
#Menghitung a,b dan c
a = int(input("Masukkan Nilai a: "))
b = int(input("Masukan Nilai b: "))
c = int(input("Masukan Nilai c: "))
rumus = (a)*(b)/(a+c)
print(".................")
print("Hasil perhitungan pada a dan b")
print(".................")
print("nilai a: ",a)
print("nilai b: ",b)
print("nilai c: ",c)
print("nilai rumus: ",rumus)
#Menghitung Luas Trapesium
t = int(input("Masukkan Nilai t: "))
a = int(input("Masukan Nilai a: "))
b = int(input("Masukan Nilai b: "))
rumus = 1/2*t*(a+b)
print(".................")
print("Hasil perhitungan pada luas trapesium")
print(".................")
print("nilai t: ",t)
print("nilai a: ",a)
print("nilai b: ",b)
print("nilai rumus: ",rumus)
#Menghitung Keliling Lingkaran
r = int(input("Masukkan Nilai r: "))
keliling = 2*22/7*r
print(".................")
print("Hasil perhitungan pada keliling lingkaran")
print(".................")
print("nilai r: ",r)
print("nilai keliling: ",keliling)
#Menghitung Luas Lingkaran
r = int(input("Masukkan Nilai r: "))
luas = 22/7*r*r
print(".................")
print("Hasil perhitungan pada keliling lingkaran")
print(".................")
print("nilai r: ",r)
print("nilai luas: ",luas)
